// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Currency is the predicate function for currency builders.
type Currency func(*sql.Selector)

// Reward is the predicate function for reward builders.
type Reward func(*sql.Selector)
